### ISSUE TITLE
Relax rich requirement

### ISSUE THREAD

**Issue by nmichlo** [tryolabs/norfair#125] opened 2022-06-21 10:38 UTC
Forfar currently requires rich `>=9,<10`, can this be relaxed/updated to make it more compatible with dependency resolution for other libraries?

**Comment by dekked** [comment] 2022-06-27 19:48
Duplicate of #104. I'll close this issue and we'll try to prioritize it better.

**Closed by dekked** 2022-06-27 19:48 UTC
Labels: enhancement
